jobs:

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Run Docker image
        run: docker run -it --name hello-world -d -p 9080:9080 ghcr.io/${{ github.repository }}:${{ github.sha }}
       


on:
  push:
    if: github.ref_name == github.event.repository.default_branch
